server:
  port: 8082
  servlet:
    context-path: "/api-reserva"

spring:
  application:
    name: apireserva-service
  datasource:
    url: jdbc:mysql://db:3306/reservas_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: vinicius@123

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true
  rabbitmq:
    addresses: amqps://cxsjvvjz:cfT5rAZ6xs1gg2R-I0gTIQ8RB9jVgFPh@chimpanzee.rmq.cloudamqp.com/cxsjvvjz

apireserva:
  api:
    url:
      usuario: "http://apireserva-usuario-service"
  broker:
    exchange:
      userEventExchange: apireserva.eventoDeUsuario
    queue:
      userEventQueue:
        name: apireserva.eventoDeUsuario.ms.reserva

ead:
  serviceRegistry:
    username: serviceregistry
    password: "ead123sr"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
