
server:
  port: 8082
  servlet:
    context-path: '/api-reserva'

spring:
  application:
    name: apireserva-reserva-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microsservicos-reserva
    username: postgres
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://cxsjvvjz:au7bfHJoqYGYvIfrDjsGuGVLTSw0gYrm@chimpanzee.rmq.cloudamqp.com/cxsjvvjz

apireserva:
  api:
    url:
      usuario: 'http://apireserva-usuario-service'
  broker:
    exchange:
      userEventExchange: apireserva.eventoDeUsuario
    queue:
      userEventQueue:
        name: apireserva.eventoDeUsuario.ms.reserva

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost